[2024-05-13T03:54:17.452+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T03:54:17.587+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v012.push_csv_file_data_to_postgres scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-13T03:54:17.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v012.push_csv_file_data_to_postgres scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-13T03:54:17.607+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-13T03:54:17.658+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): push_csv_file_data_to_postgres> on 2024-05-12 00:00:00+00:00
[2024-05-13T03:54:17.679+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v012', 'push_csv_file_data_to_postgres', 'scheduled__2024-05-12T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/postgres_hooks.py', '--cfg-path', '/tmp/tmpyogzl_91']
[2024-05-13T03:54:17.683+0000] {standard_task_runner.py:91} INFO - Job 171: Subtask push_csv_file_data_to_postgres
[2024-05-13T03:54:17.693+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=311) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-13T03:54:17.694+0000] {standard_task_runner.py:63} INFO - Started process 325 to run task
[2024-05-13T03:54:17.850+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks_v012.push_csv_file_data_to_postgres scheduled__2024-05-12T00:00:00+00:00 [running]> on host dab92a57e2e4
[2024-05-13T03:54:18.256+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myself' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v012' AIRFLOW_CTX_TASK_ID='push_csv_file_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T00:00:00+00:00'
[2024-05-13T03:54:18.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T03:54:18.331+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-13T03:54:18.333+0000] {logging_mixin.py:188} INFO - Error: connection to server at "172.23.0.2", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-05-13T03:54:18.333+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-13T03:54:18.334+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T03:54:18.364+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v012, task_id=push_csv_file_data_to_postgres, run_id=scheduled__2024-05-12T00:00:00+00:00, execution_date=20240512T000000, start_date=20240513T035417, end_date=20240513T035418
[2024-05-13T03:54:18.397+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-13T03:54:18.437+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T03:54:18.439+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
