[2024-05-09T09:38:57.895+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T09:38:57.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.push_csv_file_data_to_postgres scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T09:38:57.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.push_csv_file_data_to_postgres scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T09:38:57.951+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-09T09:38:57.970+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): push_csv_file_data_to_postgres> on 2024-05-08 00:00:00+00:00
[2024-05-09T09:38:57.977+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9805) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T09:38:57.978+0000] {standard_task_runner.py:63} INFO - Started process 9806 to run task
[2024-05-09T09:38:57.977+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'push_csv_file_data_to_postgres', 'scheduled__2024-05-08T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/postgres_hooks.py', '--cfg-path', '/tmp/tmp06lvl9i1']
[2024-05-09T09:38:57.979+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask push_csv_file_data_to_postgres
[2024-05-09T09:38:58.020+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.push_csv_file_data_to_postgres scheduled__2024-05-08T00:00:00+00:00 [running]> on host dab92a57e2e4
[2024-05-09T09:38:58.097+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myself' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v02' AIRFLOW_CTX_TASK_ID='push_csv_file_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T00:00:00+00:00'
[2024-05-09T09:38:58.098+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T09:38:58.119+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-09T09:38:58.120+0000] {logging_mixin.py:188} INFO - Error: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-05-09T09:38:58.120+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T09:38:58.121+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T09:38:58.128+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v02, task_id=push_csv_file_data_to_postgres, run_id=scheduled__2024-05-08T00:00:00+00:00, execution_date=20240508T000000, start_date=20240509T093857, end_date=20240509T093858
[2024-05-09T09:38:58.151+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T09:38:58.168+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T09:38:58.170+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
