[2024-05-09T10:10:08.670+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T10:10:08.716+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v07.push_csv_file_data_to_postgres scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T10:10:08.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v07.push_csv_file_data_to_postgres scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T10:10:08.728+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-09T10:10:08.750+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): push_csv_file_data_to_postgres> on 2024-05-08 00:00:00+00:00
[2024-05-09T10:10:08.759+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11468) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T10:10:08.760+0000] {standard_task_runner.py:63} INFO - Started process 11469 to run task
[2024-05-09T10:10:08.759+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v07', 'push_csv_file_data_to_postgres', 'scheduled__2024-05-08T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/postgres_hooks.py', '--cfg-path', '/tmp/tmpqc5lqf7l']
[2024-05-09T10:10:08.761+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask push_csv_file_data_to_postgres
[2024-05-09T10:10:08.816+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks_v07.push_csv_file_data_to_postgres scheduled__2024-05-08T00:00:00+00:00 [running]> on host dab92a57e2e4
[2024-05-09T10:10:08.908+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myself' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v07' AIRFLOW_CTX_TASK_ID='push_csv_file_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T00:00:00+00:00'
[2024-05-09T10:10:08.909+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T10:10:08.933+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-09T10:10:08.937+0000] {logging_mixin.py:188} INFO - hello hi
[2024-05-09T10:10:08.937+0000] {logging_mixin.py:188} INFO - Error: [Errno 2] No such file or directory: 'data/Orders.csv'
[2024-05-09T10:10:08.937+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T10:10:08.938+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T10:10:08.947+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v07, task_id=push_csv_file_data_to_postgres, run_id=scheduled__2024-05-08T00:00:00+00:00, execution_date=20240508T000000, start_date=20240509T101008, end_date=20240509T101008
[2024-05-09T10:10:08.974+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T10:10:08.991+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T10:10:08.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
